version: '3.8'

services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDC_INIT_PORT}:${DOCKER_INFLUXDC_INIT_PORT}

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}


  server-docker:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - influxdb

volumes:
  influxdb-storage:
  grafana-storage:
